version: '3'

services:
  postgres:
    extends:
      file: ./db/docker-compose.yml
      service: postgres

  # pg-admin:
  #   image: dpage/pgadmin4:7
  #   env_file:
  #     - postgres.dev.env
  #   ports: 
  #     - "5050:5050"

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "3030:3030"
    depends_on:
      - postgres

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

